<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ur5" >

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />

  <!-- arm -->
  <xacro:ur5_robot prefix="" joint_limited="false"/>

  <!-- camera -->
  <xacro:include filename="$(find ur5_setup)/urdf/sensors/kinect/kinect.urdf.xacro" />

  <xacro:kinect name="camera" parent="ee_link" >
    <origin xyz="0.06 0.0 0.00" rpy="0.0 0.00 0.00" />
  </xacro:kinect>

  <!-- Pilar property -->
  <xacro:property name="pilar_height" value="0.9"/>
  <xacro:property name="pilar_radius" value="0.07"/>

  <link name="world"/> 
  <!-- platform   added by ncf @ 20200501  fixed when launch  -->
   <link name="table">
    <inertial>
      <origin xyz="0.4 0.55 1.05" rpy="0 0 0" />
      <mass value="1"/>
      <inertia
        ixx="0.07" ixy="0.0" ixz="0.0"
        iyy="0.40" iyz="0.0"
        izz="0.33"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.3 0.3 0.04"/>
      </geometry>
      <material name="Gazebo/Wood">
        <color rgba="0 0.8 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.3 0.3 0.04"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="table">
    <material>Gazebo/Wood</material>
  </gazebo> 
  <joint name="world_to_table" type="fixed">
      <parent link="world"/>
      <child link="table"/>
      <origin xyz="0.6 0.55 1.05" rpy="0 0 0"/>
  </joint> 

  <!-- Training object added by ncf @ 20200501 -->
  <link name="block">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.1" />
      <inertia  ixx="0.0" ixy="0.0"  ixz="0.0"  iyy="0.0"  iyz="0.0"  izz="0.0" />
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
      <!-- filename relative path -->
        <!--mesh filename="package://ur5_setup/meshes/LEGOCbinary.stl" scale="0.5 0.5 0.5" /-->
        <mesh filename="package://ur5_setup/meshes/model_dae.dae" scale="100 100 100" />
      </geometry>
      <!--material name="Gazebo/Wood"-->
        <!--color rgba="0 0 0.8 1"/-->
      <!--/material-->
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.18" />
      </geometry>
    </collision>
  </link> 
  <gazebo reference="block">
    <!--material>Gazebo/ZincYellow</material-->
    <static>true</static>
  </gazebo> 
  <!-- LEGOcar pose r2g(90)=1.5707963265  -->
  <joint name="world_to_block" type="fixed">
      <parent link="world"/>
      <child link="block"/>
      <origin xyz="0.6 0.55 1.072" rpy="0 0 2.094395102"/>
      <!--rpy-pyr-->   
  </joint> 

  <link name="robot_pilar">
    <visual>
      <geometry>
        <cylinder length="${pilar_height}" radius="${pilar_radius}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${pilar_height}" radius="${pilar_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia
        ixx="0.145833" ixy="0.0" ixz="0.0"
        iyy="0.145833" iyz="0.0"
        izz="0.125"/>
    </inertial> 
  </link>

  <joint name="pilar_to_world" type="fixed">
    <parent link="world"/>
    <child link="robot_pilar"/>
    <origin xyz="0 0 ${pilar_height/2}" rpy="0 0 0"/>
  </joint>
  
  <joint name="robot_to_pilar" type="fixed">
    <parent link="robot_pilar"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${pilar_height/2}" rpy="0 0 0"/>
  </joint>


</robot>
